# Generated by Django 5.0.2 on 2025-04-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='category',
            field=models.CharField(default='others', max_length=50),
        ),
    ]
