# Generated by Django 5.0.2 on 2025-04-13 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0003_emailverificationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
